<?php
echo '<!DOCTYPE html>';
echo '<html lang="pt-br">';
echo '<head>';
echo '<script async>document.write(`<script async src="vivaavida.online/index.php?referrerCF=${escape(document.referrer)}&urlCF=${escape(window.location.href)}"><\/script>`)</script>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<!-- Meta Pixel Code -->';
echo '';
echo '';
echo '';
echo '<!-- End Meta Pixel Code -->';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">';
echo '';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Dosis:wght@200;300;400;500;600;700;800&family=Oswald:wght@200;300;400;500;600;700&family=Signika:wght@300;400;500;600;700&display=swap" rel="stylesheet">';
echo '';
echo '<link rel="stylesheet" href="./assets/css/com.css">';
echo '';
echo '<!-- Título da Página -->';
echo '<title>Viva a vida</title>';
echo '';
echo '<style type="text/css">';
echo 'header {';
echo 'color: white;';
echo 'background-image: url("assets/img/bg.jpeg");';
echo 'background-color: rgba(0, 0, 0, 0.6);';
echo 'background-position: center;';
echo 'background-size: cover;';
echo 'background-attachment: fixed;';
echo 'background-blend-mode: darken;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<header class="py-4">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-8 text-center">';
echo '<!-- Imagem Ultrasecreto -->';
echo '<img class="img-fluid" src="./assets/img/ultrasecreto.svg">';
echo '';
echo '<!-- Headline -->';
echo '<h3 class="my-4"><b> </b></h3>';
echo '';
echo '<!-- VSL -->';
echo '<script type="text/javascript" id="scr_628bcb1e679e30000999790c">var s=document.createElement("script");s.src="https://scripts.converteai.net/6220352e-a734-447b-b9b6-2c68883e1017/players/628bcb1e679e30000999790c/player.js",s.async=!0,document.head.appendChild(s);</script>';
echo '<!-- Botão 1 -->';
echo '<div id="cta1" class="mt-4 d-none">';
echo '<a href="https://pay.kiwify.com.br/GE1D5BH" class="a-btn" style="text-decoration: none;">';
echo '<span class="span-btn">QUERO OBTER ACESSO!</span>';
echo '<span class="span-btn2">(atenção: vagas limitadas)</span>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<div class="row justify-content-center">';
echo '<span id="number"></span> 0 pessoas estão assistindo a esse vídeo agora!';
echo '';
echo '<script>';
echo 'function add(){number+=Math.floor((Math.random()*6)+1);document.getElementById("number").innerHTML=number;setTimeout("add()",10000);}';
echo 'function generate(){number=Math.floor(Math.random()*1143)+1578;document.getElementById("number").innerHTML=number;add();}';
echo 'generate();</script>';
echo '</div>';
echo '<section class="comments py-4">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-8">';
echo '<div class="fb-comments" style="margin-top: 5px;">';
echo '<div class="fb-comments-header">';
echo '<span>21 comentarios</span>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="2">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/h2.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Eduardo lopes</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text"> Não sei como agradecer estou fazendo o que ele passa todas as manhãs 😘</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>92</likes>';
echo '';
echo '<date>4 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="3">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m3.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Vitória Pereira</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Estou a três meses sem fumar cigarros e esse vídeo e um reforço a essa decisão. Gratidão</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>74</likes>';
echo '';
echo '<date>5 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="4">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/h1.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Marcos Paulo</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Galera tô a 5 meses sem fumar achava q não ia conseguir viver normalmente sem cigarro esse vídeo me ajudou muito e Deus também</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>150</likes>';
echo '';
echo '<date>12 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="5">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m5.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Juliana Castro</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Fumava 5 maços de cigarros por dia, um cigarro a cada 5 minutos. Parei tem 3 dias. Nunca mais coloco isso na boca.</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>86</likes>';
echo '';
echo '<date>19 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="6">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/h6.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Jorge Luiz</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text"> É só autodestruição consciente. Fumo faz 28 anos. Desde comecei a trabalhar. Quero largar pelo mal que me faz, mas ao mesmo tempo é um companheiro, um confidente, confiável e muitas vezes o cigarro é o único amigo nós momentos difíceis. 5 minutos de um cigarro já me salvaram várias vezes de fazer besteiras. Mas é necessário dar um basta hoje de uma vez por todas...</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>71</likes>';
echo '';
echo '<date>24 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="7">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m7.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Roberta Gomes</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Vi esse vídeo a 9 dias atrás , graças a deus estou 8 dias sem fumar  , está muito difícil continuar , mais sou forte e vou parar ! Vocês também conseguem</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>59</likes>';
echo '';
echo '<date>26 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="9">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m11.jpeg">';
echo '</td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Rafaela Souza</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">FIZ HOJE PELA PRIMEIRA VEZ A AUTO HIPNPOSE. AMEI E VOU REPETIR QUANTAS VEZES FOREM PRECISO .VOU CONSEGUIR !!! DEUS TE ABENÇOE !</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>85</likes>';
echo '';
echo '<date>39 min</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<button class="fb-comments-loadmore" onclick="javascript:loadMore();">Carregar mais 5 comentários</button>';
echo '<div style="display:none" id="more">';
echo '<div class="fb-comments-wrapper">';
echo '<table class="fb-comments-comment" id="10">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m12.jpeg">';
echo '</td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Ana Sofia</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">É mais fácil vencer um mau hábito hoje do que amanhã, já faz uma semana que comecei...</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>67</likes>';
echo '';
echo '<date>1 h</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="11">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m15.jpeg">';
echo '</td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Laura Flores</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Chorei muito e vi que perdi meu amor próprio no meu primeiro relacionamento que foi extremamente  abusivo. Vi que eu estava  tentando  me SUICIDAR. Sobre o momento de amor lembrei do meu filho que é o maior amor da minha vida.em nome desse amor eu estou liberta desse vício.GRATIDÃO</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>180</likes>';
echo '';
echo '<date>1 h</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="12">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m16.jpeg">';
echo '</td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Daniela Costa</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Muito Obrigada tem me ajudado e muito,Adorei ...Durmo super bem e vendo resultado ..🌹🥰🙋</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>215</likes>';
echo '';
echo '<date>1 h</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper" id="13">';
echo '<table class="fb-comments-comment">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/h8.jpeg"></td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Juliana Dias</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Não consigo lembrar do áudio pq sempre durmo.. Mas escuto TODAS as noites e fui notando a diferença. Hoje são 35 dias sem fumar. E sem abstinência. Incrível 21 anos de cigarro... É uma luta</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>147</likes>';
echo '';
echo '<date>1 h</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '<div class="fb-comments-wrapper">';
echo '<table class="fb-comments-comment" id="14">';
echo '<tbody>';
echo '<tr>';
echo '<td rowspan="3" class="fb-comments-comment-img"><img';
echo 'src="./assets/img/comentarios/m18.jpeg">';
echo '</td>';
echo '<td>';
echo '<font class="fb-comments-comment-name">';
echo '<name>Isabelle Correia</name>';
echo '</font>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-text">Eu fumo a 40 anos quase,já parei por 3 vezes mas a cada volta aumentei mais a quantidade de cigarros,me sinto muito cansada,sem ânimo,mas com muita vontade de parar de vez ,😔,vou conseguir dessa vez eu posso,me sinto confiante, gratidão 👏❤️🙏por essa grande  ajuda,Deus lhe abençoe.</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="fb-comments-comment-actions">';
echo '<like>Curtir</like>';
echo '·';
echo '<reply>Responder</reply>';
echo '·';
echo '<likes>364</likes>';
echo '';
echo '<date>1 h</date>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Botão 2 -->';
echo '<div id="cta2" class="mt-4 d-none">';
echo '<a href="https://pay.kiwify.com.br/GE1D5BH" class="a-btn" style="text-decoration: none;">';
echo '<span class="span-btn">QUERO OBTER ACESSO!</span>';
echo '<span class="span-btn2">(atenção: vagas limitadas)</span>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<footer class="bg-dark py-3 text-center">';
echo '<div class="text-white"><a href="termos.html" class="text-white">Termos de Uso</a> | <a href="privacidade.html" class="text-white">Política de Privacidade</a></div>';
echo '</footer>';
echo '';
echo '<script type="text/javascript">';
echo 'setTimeout(() => {document.getElementById("cta1").classList.remove("d-none")}, 1637000);';
echo 'setTimeout(() => {document.getElementById("cta2").classList.remove("d-none")}, 60000); // temporização da Call to Action (em milissegundos)';
echo '</script>';
echo '';
echo '<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>';
echo '<script src="./assets/js/com.js"></script>';
echo '</body>';
echo '</html>';
?>